config/routes.rb
Rails.application.routes.draw do

  root to: 'toppages#index'

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  delete 'tasks/:id', to: 'tasks#destroy', as: 'tasks_del'

  resources :tasks
  resources :users
  resources :sessions, only: [:edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
	validates :content, presence: true, length: {maximum:255}
	validates :status, presence: true, length: {maximum:10}
	validates :user, presence: true, length: {maximum:255}
	
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email.downcase! }
	
	has_many :tasks, dependent: :destroy
	has_secure_password
	
	validates :name, presence: true, length: { maximum: 50 }
	validates :email, presence: true, length: {maximum: 255},
										format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i},
										uniqueness: {case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
  	unless logged_in?
  		redirect_to login_url
  	end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  #画面必要
  def new
  end
  
  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    
    if login(email, password)
      flash[:success] = "ログインしました"
      redirect_to @user
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました"
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  #before_action :set_params, only:[:show, :edit, :update, :destroy]
  before_action :set_params, only:[:show, :edit]
  before_action :correct_user, only:[:show, :edit, :update, :destroy]

  #画面必要
  def index
    @tasks = Task.all.page(params[:page]).per(15)
  end

  #画面必要
  def show
    #set_params
    #@task = Task.find(params[:id])
    @user = User.find_by(id: current_user)
  end

  #画面必要
  def new
    @task = Task.new
  end

  def create
    #@task = Task.new(post_params)
    @task = current_user.tasks.build(post_params)

    if @task.save
      flash[:success] = "The registration is succeeded"
      redirect_to @task

      #TBD
      #redirect_to root_path
    else
      flash.now[:danger] = "The registration is failed"
      render :new
    end
  end

  #画面必要
  def edit
    set_params
    #@task = Task.find(params[:id])
    @user = User.find_by(id: current_user)
  end

  def update
    #@task = current_user.tasks.build(post_params)
    set_params
    #@task = Task.find(params[:id])
    
    if @task.update(post_params)
      flash[:success] = "The registration is succeeded"

      redirect_to user_path(current_user)
    
    else
      flash.now[:danger] = "The registration is failed"
      render :edit
    end  
  end

  def destroy
    #correct_user
    #set_params
    #@task = Task.find(params[:id])
    #@task = Task.find_by(id: current_user)
    @task.destroy
    
    flash[:success] = "The task is deleted"
    #redirect_back(fallback_location: root_path)
    #redirect_to root_url
    redirect_to user_path(current_user)
  end

  private
  
  def set_params
    @task = Task.find(params[:id])
  end

  def post_params
    params.require(:task).permit(:content, :status)
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    #redirect_to root_url if @task.user != current_user
    unless @task
      redirect_to root_url
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_params, only: [:show, :edit, :update, :destroy]
  before_action :require_user_logged_in, only: [:index, :show]

  
  #画面必要
  def index
    @users = User.all.page(params[:page]).per(10)
  end

  #画面必要
  def show
    #before_action

    #<<-PAGE
    if session[:user_id] == @user.id
      return @user
    else
      redirect_to root_url
    end
    #PAGE
  end

  #画面必要
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(post_params)
    
    if @user.save
      flash[:success] = "ユーザの登録が完了しました"
      
      #追加
      session[:user_id] = @user.id
      
      redirect_to @user
    else
      flash.now[:danger] = "ユーザの登録に失敗しました"
      render :new
    end
  end

  #画面必要
  def edit
    #before_action
  end
  
  def update
    #before_action
    
    if !@user == nil && @user.update(post_params)
      flash[:success] = "登録情報を更新しました"
      redirect_to @user
    else
      flash.now[:danger] = "登録情報の更新が出来ませんでした"
      render :edit
    end
  end
  
  def destroy
    #before_action
    
    @user.destroy
    
    flash[:success] = "登録情報を削除しました"
    session[:user_id] = nil
    redirect_to root_url
  end
  
  private
  
  def set_params
    @user = User.find(params[:id])
  end

  def post_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

<<-PAGE	
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end
	
	def logged_in?
		if session[:user_id]
			return true
		else
			return false
		end
	end
PAGE
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		if session[:user_id]
			return true
		else
			return false
		end
	end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_url(user, option = {size:80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = option[:size]
		"https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
	end
end

app/views/layouts/_error_messages.html.erb
<% if message.errors.any? %>
	<div class="alert alert-warning">
		<ul>
			<% message.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message|%>
    <div class="alert alert-<%= type %>"><%= message %></div>
<% end %>

app/views/layouts/_navber.html.erb
<header>
	<nav class="navbar navbar-inverse navbar-static-top">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				
				<%# top page%>
				<% if logged_in? %>
					<%= link_to user_path(current_user) do %>
						<div class="navbar-brand">
							<span class="glyphicon glyphicon-tasks"></span>
							Tasklist
						</div>
					<% end %>
				<% else %>
					<a href="/" class="navbar-brand">
						<span class="glyphicon glyphicon-tasks"></span>
						Tasklist
					</a>
				<% end %>
			</div>
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					<% if logged_in? %>
						<li><%= link_to "プロフィール", user_path(current_user) %></li>
						<li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
					<% else %>
						<li><%= link_to '新規登録', signup_path %></li>
						<li><%= link_to 'ログイン', login_path %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewpoint" content="width=device-width, initial-scale=1">

    <title>Tasklist</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
  </head>

  <body>
    <div>
      <%= render 'layouts/navber' %>
      
      <div class="container">
        <%= render 'layouts/flash_messages' %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="row">
    <div class="col-xs-12  col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">
        <h1><%= @user.name %>さんのタスク編集ページ</h1>
    
        <%= render 'layouts/error_messages', message: @task %>
        
        <h3>id:<%= @task.id %></h3>
        <%= form_for(@task) do |f| %>
            <%= f.label :status, '状態' %>
            <%= f.select :status, ["未着手", "実施中", "完了"], class:"selectpicker" %>
            <%#= f.text_field :status %>
            <br>
            <%= f.label :content, 'タスク' %>
            <%= f.text_field :content, class:"form-control" %>
        
            <%= f.submit '保存する', class:"btn btn-default" %>
            <%= link_to '詳細に戻る', task_path(@task), class:"btn btn-default" %>
            <%= link_to '一覧に戻る', user_path(current_user), class:"btn btn-default" %>
        <% end %>
    </div>
</div>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>


<% if @tasks.any? %>
    <table class="table table-striped">
        <thead>
            <th>id</th>
            <th>状態</th>
            <th>内容</th>
        </thead>
        <tbody>
            <% @tasks.each do |task| %>
                <tr>
                    <td><%= link_to task.id, task %></td>
                    <td><%= task.status %></td>
                    <td><%= task.content %></td>
                </tr>
            <% end %>                
        </tbody>
    </table>
    <%= paginate @tasks %>
<% end %>

</br>
<%= link_to '新規登録', new_task_path, class:"btn btn-primary" %>


<% if false %>
    <% @tasks.each do |task| %>
        <ul>
            <li>
                id:<%= link_to task.id, task %> 状態：<%= task.status %> ：内容:<%= task.content %>
            </li>
        </ul>
    <% end %>
<% end %>

app/views/tasks/new.html.erb
<div class="row">
    <div class="col-xs-12  col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">
        <h1>新規タスク登録</h1>
        <%= render 'layouts/error_messages', message: @task %>
        
        <%= form_for(@task) do |f| %>
            <div class="form-group">
                <%= f.label :status, '状態' %>
                <%= f.select :status, [["未着手"], ["実施中"], ["完了"]]%>
            </div>
            <div class="form-group">
                <%= f.label :content, 'タスク' %>
                <%= f.text_field :content, class:"form-control col-size" %>
            </div>
        
            <%= f.submit '登録する', class:"btn btn-default" %>
            <%= link_to '一覧に戻る', user_path(current_user), class:"btn btn-default" %>
        <% end %>
    </div>
</div>

app/views/tasks/show.html.erb
<h1><%= @user.name %>さんのタスク詳細ページ</h1>

<table class="table table-bordered">
	<tr>
		<td>id</td>
		<td><%= @task.id %></td>
	</tr>
	<tr>
		<td>状態</td>
		<td><%= @task.status %></td>
	</tr>
	<tr>
		<td>内容</td>
		<td><%= @task.content %></td>
	</tr>
</table>

<%= link_to '一覧に戻る', user_path(current_user), class:"btn btn-default" %>
<%= link_to '編集する', edit_task_path, class:"btn btn-default" %>
<%= link_to '削除する', @task, method: :delete, data: {confirm: "Are you OK?"}, class:"btn btn-danger" %>

app/views/toppages/index.html.erb
<%# ここは全体のトップページ　%>
<%# ログイン前/後で表示内容を変える　%>
<%# ログイン前：ユーザ登録/ログイン　%>
<%# ログイン後：本画面は使わない　tasks_path　%>

<%# ログイン前：ユーザ登録/ログイン　%>
<div class="center jumbtron">
	<div class="text-center">
		<h1>タスク管理アプリ</h1>
		<h3>あたなのタスクを登録・管理できます</h3>
		<div id="o-margin">
			<%= link_to '新規登録', signup_url, class:"btn btn-default" %>
			<%= link_to 'ログイン', login_url, class:"btn btn-default" %>
		</div>
	</div>
</div>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
	<div class="form-group">
		<%= f.label :name, '名前' %><br>
		<%= f.text_field :name, class:"form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :email, 'Eメールアドレス' %><br>
		<%= f.email_field :email, class:"form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :password, 'パスワード' %><br>
		<%= f.password_field :password, class:"form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :password_confirmation, 'パスワードをもう1度入力してください' %><br>
		<%= f.password_field :password_confirmation, class:"form-control" %>
	</div>
	
	<br>
	<%= f.submit '登録する', class:"btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<%# ユーザの登録情報　編集画面 %>

<div class="row">
  <div class="col-xs-12  col-md-6 col-md-offset-3">
		<h1>ユーザ情報　編集</h1>
    <%= render 'layouts/error_messages', message: @user %>
    
    <%= render 'form', user: @user %>
  </div>
</div>

app/views/users/index.html.erb
<%# ユーザの一覧画面 %>
<%# ログイン判定は@userにパラメータが入っているか否かで判定する %>

<%# ★★★パーシャルにするかは別途 %>

<%# ログイン判定 %>
<% if @users.any? %>
<%# ログイン後 %>

	<ul class="media-list">
		<% @users.each do |user| %>
			<li class="media">

				<%# gravatorから画像を取得する %>
				<div class="media-left">
					<img class="media-object img-rounded" src="<%= gravatar_url(user, {size: 50}) %>" alt="">
				</div>
				<div class="media-body">
					<div>
						<%= user.name%>
					</div>
					<div>
						<!--p><%= link_to user.name + 'さんの詳細情報', @user %></p-->
						<p><%= link_to "#{user.name}さんの詳細情報", @user %></p>
					</div>
				</div>
			</li>
		<% end %>
	</ul>
	<%= paginate @users %>
	
<% else %>
<%# ログイン前 %>
<%# ★★★ログイン前に対するフラッシュの追加が必要 %>
	flash[:danger] = "ログインが必要です"
	redirect_to new_session_url
<% end %>

app/views/users/new.html.erb
<%# ユーザの新規登録画面 %>

<div class="row">
	<div class="col-xs-12  col-md-6 col-md-offset-3">
		<h1>新規ユーザ登録</h1>
		<%= render 'layouts/error_messages', message: @user %>
		
		<%= render 'form', user: @user %>
	</div>
</div>

app/views/users/show.html.erb
<%# ユーザの詳細画面 %>

<div class="row">
	<aside class="col-xs-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title"><%= @user.name %></h3>
			</div>
			<div class="panel-body">
				<img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
			</div>
		</div>
			<div>
				<%= link_to '登録情報の編集', edit_user_url, class:"btn btn-success" %>
				<%= link_to '登録情報の削除', @user, method: :delete, data: {confirm: "登録されているタスクも消えますが、よろしいですか?"}, class:"btn btn-danger" %>
			</div>
	</aside>
	<div class="col-xs-8">
		<ul class="nav nav-tabs nav-justified">
			<li class="if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>タスク名 <span class="badge"><%= @count_microposts %></span><% end %></li>
		</ul>
		<ul>
    <table class="table table-striped">
      <thead>
          <th>id</th>
          <th>状態</th>
          <th>内容</th>
      </thead>
      <tbody>
      	<% @user.tasks.each do |task| %>
          <tr>
              <td><%= link_to task.id, task_path(task) %></td>
              <td><%= task.status %></td>
              <td><%= task.content %></td>
          </tr>
        <% end %>                
      </tbody>
		 </table>
		 <%#= paginate @tasks %>
		</ul>
		<div>
			<%= link_to '新規タスク登録', new_task_path, class:"btn btn-primary" %>
		</div>
	</div>
</div>